- name: installing maven
  ansible.builtin.import_role: 
    name: common
    tasks_from: maven-setup

- name: setup shipping env
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: maven package
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: mysql load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema


- name: service start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup