- name: variables from files
  #host: mongodb #managing the ansible server itself
  vars_files:
  - variables.yaml
  tasks:
  - name: priniting variables from file
    ansible.builtin.debug:
      msg: "we are learning {{NAME}}, Duration is: {{DURATION}}, Trainer is {{TRAINER}}"