- name: variables at task level
  hosts: localhost
  vars:
  - money: "150000 rs"
    land: "7 acres"
  tasks: 
  - name: inherit values from play
    ansible.builtin.debug:
    msg: "total amout is {{money}}, land is {{land}}"
  - name: inherit and override
    vars:
    - money: "200000 rs"
      houses: "3"
    ansible.builtin.debug:
    msg: "total amount is {{money}}, houses {{houses}} total land is {{land}}"