- name: install python
  ansible.builtin.import_role:
  name: common
  tasks_from: python

- name: set up payment service
  ansible.builtin.import_role: 
  name: common
  tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: service start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup