# I need to refer nodejs tasks in common folder
# catalogue is one role
# common is also another role
# I need to import a task nodejs.yaml in catalogue

- name: Install NodeJS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

- name: load {{component}} data
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mongo-schema

- name: service reload
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
