- name: Installing mysql
  hosts: mysql
  become: yes
  tasks: 
  - name: Disabling current mysql version
    ansible.builtin.command: yum module disable mysql -y

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install mysql sever
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed

  - name: start and enabled mysqld
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup mysql root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1