- name: install payment
  host: payment
  become: yes
  tasks: 
  - name: insall pyhton
    ansible.builtin.yum:
    name: "{item}"
    state: installed
    loop:
    - python36 
    - gcc 
    - python3-devel

  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc !=0
    name: create user 
    become: yes
    ansible.builtin.user: 
      name: roboshop
  
  - name: check dir exist or not
    ansible.builtin.stat:
    path: /app
  register: directory

  - name: print the directory stats
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - when: directory.stat.exists == False
    name: create dir
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading zip
    ansible.builtin.get_url:
      url: curl -L -o /tmp/payment.zip https://roboshop-builds.s3.amazonaws.com/payment.zip
      dest: /tmp

  - name: unzip roboshop
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes


  - name: install dependencies
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app

  - name: copy payment service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: deamon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: restart payment
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: true
 